### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by cjonstrup** [epoweripione/docker-php#1]
https://github.com/epoweripione/docker-php/blob/2f7f6c5bff05b48f53974788969e87ab266e95c0/php-fpm-8.1/Dockerfile#L78

If you add the UNAME variable for pdflib download url it will work for ARM (aarch64)

`    UNAME_M=$(uname -m) && \
    curl -fSL -o pdflib.tar.gz https://www.pdflib.com/binaries/PDFlib/1000/PDFlib-10.0.0p1-Linux-${UNAME_M}-php.tar.gz && \`

**Comment by epoweripione** [comment]
Fixed, since I don't use the ARM version, need more testing.

**Comment by epoweripione** [comment]
`ARM64` version added.
